- .github/workflows/build_koheesio.yaml
- .github/workflows/test.yaml
- tests/conftest.py
> updated workflows

- .github/workflows/test.yml
- src/koheesio/spark/writers/delta/batch.py
- tests/spark/writers/delta/test_delta_writer.py
DeltaTableWriter provides the option to configure the writer in MERGE mode using the output_mode_params field by providing in it a list of merge clauses in the merge_builder key. This is especially useful in case the Delta table or the DataFrame to be merged are not available upfront. Not all merge clauses were supported: the merge clause provided was being validated against a list of valid clauses which did not include whenMatchedUpdateAll and whenNotMatchedInsertAll clauses. As part of this PR:
- validation of the clauses now happens in the output_mode_params field validator (currently this is happening only when the merge is being executed)
- the list of available merge clauses is sourced directly from available methods in DeltaMergeBuilder class and now includes all of them …
> Add missing merge clauses in DeltaTableWriter

- src/koheesio/spark/readers/file_loader.py
- tests/spark/readers/test_file_loader.py
Add streaming option to FileLoader. Default behaviour is batch.
[Issue 50
](https://github.com/Nike-Inc/koheesio/issues/50)
Having a `streaming` option for the `FileLoader` would be beneficial during UT's or for people that are not on Databricks and can't make use of the Databricks proprietary `Autoloader`.
- UT's
- On Databricks
> Add streaming option to FileLoader.

- src/koheesio/integrations/spark/tableau/hyper.py
- src/koheesio/integrations/spark/tableau/server.py
- src/koheesio/spark/readers/jdbc.py
- tests/spark/integrations/snowflake/test_snowflake.py
SnowflakeReader and SnowflakeWriter have different parameter names for the table name
https://github.com/Nike-Inc/koheesio/issues/65
It would improve usability using the same parameter for the table name in both SnowflakeReader and SnowflakeWriter
We have added tests to cover the table parameter being passed as "table" instead of "dbtable"
> [FIX] - Snowflake reader and writer have different parameter names for table name 

- src/koheesio/integrations/spark/tableau/hyper.py
- Added the guidance to use `dbfs:/` scheme and configure the path for the Hyper file manually during the class initialization
- Substitute the `dbfs:` sceme with POSIX-style notation `/dbfs`, to make the path compatible with `os.walk`
#72 
Fixes the above mentioned issue, otherwise the `HyperFileDataFrameWriter` class does not work in DBX
- local tests / local code
- build wheel and install manuall on the DBX cluster, executed the code before and after fix
> [BUGFIX] Tableau Hyper generation on DBFS is broken

- src/koheesio/integrations/box.py
> 90-Bug-fix-file-encoding-box-integration

- src/koheesio/spark/writers/delta/batch.py
…but the name does (i.e. when using Databricks' Delta Connect library)
...
#101 
...
On a Databricks cluster running connet
...
> fix for DeltaMergeBuilder, when the instance doesn't check out

- src/koheesio/asyncio/__init__.py
- src/koheesio/integrations/box.py
- src/koheesio/integrations/snowflake/test_utils.py
- src/koheesio/integrations/spark/tableau/hyper.py
- src/koheesio/models/__init__.py
- src/koheesio/spark/readers/file_loader.py
- src/koheesio/spark/readers/rest_api.py
- src/koheesio/spark/transformations/__init__.py
- src/koheesio/spark/transformations/camel_to_snake.py
- src/koheesio/spark/transformations/date_time/interval.py
- src/koheesio/spark/transformations/lookup.py
- src/koheesio/spark/transformations/strings/change_case.py
- src/koheesio/spark/transformations/strings/split.py
- src/koheesio/spark/transformations/strings/trim.py
- src/koheesio/spark/transformations/uuid5.py
- src/koheesio/spark/writers/file_writer.py
- src/koheesio/steps/__init__.py
- tests/steps/test_steps.py
Enhanced the Step class and its metaclass StepMetaClass to ensure that the execute method is wrapped only once, even when inherited multiple times. Added tests to verify that the log and wrapper are called only once in such scenarios. Also, included custom metaclass examples and their respective tests.  
N/A
It was established that (under the right conditions) our code allowed the execute method to be wrapped multiple times, even though we had code in place to prevent that. This reflected outwardly by seeing log duplication. For example like this:
```bash
[1111] [2024-11-18 14:22:18,355] [INFO] [koheesio.MyCustomGreatGrandChildStep] {__init__.py:_log_start_message:307} - Start running step
[1111] [2024-11-18 14:22:18,355] [DEBUG] [koheesio.MyCustomGreatGrandChildStep] …
```
> [FIX] Accidental duplication of logs

- .gitignore
- src/koheesio/spark/readers/delta.py
Introduce private attributes for batch and stream readers to enable adding options to DeltaReader both streaming and writing.
#110 
Provide possibility to override readers, e.g. add more options to readers. 
Current tests
> [FEATURE] Enable adding options to DeltaReader both streaming and writing

- src/koheesio/integrations/snowflake/__init__.py
- tests/snowflake/test_snowflake.py
Populate account from url if not provided in SnowflakeBaseModel
#115 
Account populated from url if not provided
New tests have been added.
> [FEATURE] Populate account from url if not provided in SnowflakeBaseModel

- src/koheesio/integrations/snowflake/__init__.py
- tests/snowflake/test_snowflake.py
Snowflake python connector have a logic to get default[ root directory for configurations](https://github.com/snowflakedb/snowflake-connector-python/blob/9ddb2050cde13819a289fb6982b48431f253a53e/src/snowflake/connector/sf_dirs.py#L47): 
```python
def _resolve_platform_dirs() -> PlatformDirsProto:
"""Decide on what PlatformDirs class to use.
In case a folder exists (which can be customized with the environmental
variable `SNOWFLAKE_HOME`) we use that directory as all platform
directories. If this folder does not exist we'll fall back to platformdirs
defaults.
This helper function was introduced to make this code testable.
"""
platformdir_kwargs = {
"appname": "snowflake",
"appauthor": False,
}
snowflake_home = pathlib.Path(
os.environ.get("SNOWFLAKE_HOME", "~/.snowflake/"),
).expanduser() …
```
> hotfix: snowflake python connector default config dir

- src/koheesio/integrations/box.py
- tests/spark/integrations/box/test_box.py
Fix bug on csvreader for box integration.
> [BUGFIX] 144-BOX-CSVREADER

- src/koheesio/spark/transformations/__init__.py
- src/koheesio/spark/transformations/camel_to_snake.py
- tests/spark/transformations/test_transform.py
- tests/spark/transformations/test_transformation.py
Fix ColumnConfig in ColumnsTransformation
- ColumnConfig defaults in ColumnsTransformation for run_for_all_data_type and limit_data_type were not working correctly
+ Added more efficient Spark 3.4 supported operation for CamelToSnakeTransformation
#85 
...
N/A
> [BUGFIX] ColumnConfig defaults in ColumnsTransformation for run_for_all_data_type and limit_data_type were not working correctly

- src/koheesio/models/__init__.py
- tests/models/test_models.py
Add partial classmethod to Koheesio' BaseModel to enhance customization. 
This update introduces a new partial method to the BaseModel class, allowing developers to override or extend base functionality easily. This change promotes better modularity and flexibility in creating reusable components within the data pipeline framework.
Additionally, fixed any mypy alerts in the files touched.
N/A
It was always possible to just wrap a BaseModel (or Step) in a `functools.partial` call. With this PR, it brings this functionality straight to the BaseModel class.
Additional Unit Test has been added.
```python
class SomeStep(BaseModel):
foo: str
bar: int
partial_step = SomeStep.partial(foo="default_foo")
some_step = partial_step(bar=42)
print(some_step.foo)  # prints 'default_foo' …
```
> [FEATURE] add partial method to BaseModel

- src/koheesio/spark/utils/common.py
- src/koheesio/steps/http.py
- tests/steps/test_http.py
Adds support for including a bearer token in the HTTP module headers along with proper masking to ensure the token's 'secret' status is maintained.
- Added default ability to include a bearer token in the headers.
- Implemented masking for the bearer token in any output to maintain its 'secret' status.
- Updated the get_headers method in the Http module to accommodate these changes.
- Added unit tests
Closes #157 
The current implementation of get_headers did not support adding a bearer token by default and did not properly mask the token in the output. This posed a security risk. This PR addresses these issues by adding default support for bearer tokens and ensuring that they are masked in any output.
Unit tests were added.
> [FEATURE] Enhance HttpStep to support bearer token and improve header handling

- pyproject.toml
- src/koheesio/integrations/snowflake/__init__.py
- src/koheesio/spark/readers/hana.py
- src/koheesio/spark/readers/jdbc.py
- src/koheesio/spark/readers/teradata.py
- src/koheesio/spark/transformations/hash.py
- src/koheesio/steps/__init__.py
- tests/spark/integrations/snowflake/test_sync_task.py
- tests/spark/readers/test_jdbc.py
- tests/spark/transformations/test_hash.py
- tests/steps/test_http.py
- tests/steps/test_steps.py
This PR addresses the issue of duplicate logs when using a `super()` call in the execute method of a Step class under the specific condition where `super()` was not pointing to the direct ancestor of the called `Step`. The problem was caused by the `_is_called_through_super` method of the `StepMetaClass` not being able to inspect beyond the immediate ancestor of the called object. 
This fix involves updating the `_is_called_through_super` method to traverse the entire method resolution order (MRO) and correctly identify if the `execute`-method is called through `super()` in any parent class of its direct ancestry. 
Additionally, the `_execute_wrapper` method was updated to ensure logging is only triggered once per execute call.
Closes #167 
This change is required to prevent duplicate …
> [BUGFIX] Fix log duplication when using specific super call

- .github/workflows/test.yml
- docs/releases/0.10.md
- src/koheesio/__about__.py
- src/koheesio/logger.py
- src/koheesio/models/__init__.py
- src/koheesio/sso/okta.py
- src/koheesio/utils/__init__.py
- tests/sso/test_okta.py
* Addressed a bug in the OktaAccessToken class related to headers setup by ensurin they remain blank.
* Also fixed an issue with secret masking in OktaAccessToken
* Added experimental to `SecretStr.__format__` method for clarification
* Updated version to 0.10.1 
* and documented changes in release notes.
Several tests were added to cover the newly discovered edge cases and logging issues.
> [BUGFIX] OktaAccessToken bug and enhance logging and tests

- .github/workflows/test.yml
- src/koheesio/spark/writers/delta/batch.py
- tests/spark/writers/delta/test_delta_writer.py
There was a small error in validating merge builder type when using the `merge_builder` param with `DeltaTableWriter`. It required that the value passed was either a `list` or a `delta.tables.DeltaMergeBuilder` instance so validation failed when an instance of `delta.connect.tables.DeltaMergeBuilder` was passed.
One cannot pass a correct DeltaMergeBuilder instance as a merge builder for `DeltaTableWriter` if it's not a `delta.tables.DeltaMergeBuilder` instance or a `list`. Connect merge builders should also be supported.
4 dedicated test cases have been added to test the merge builder validation.
> Fixed checking merge builder type in DeltaTableWriter

- src/koheesio/integrations/spark/snowflake.py
- tests/spark/integrations/snowflake/test_sync_task.py
Ensure a new INSERT is synchronized to Snowflake, even when a match is already found.
When a delta table is VACUUMed before a sync to Snowflake was triggered, a updated record will be considered as an "INSERT" record. However the target table might already contain this record. This PR ensures that this record is still updated as would be desired.
When a delta table is VACUUMed before a sync to Snowflake was triggered, a updated record will be considered as an "INSERT" record. However the target table might already contain this record. This PR ensures that this record is still updated as would be desired.
This was a bug in our code. This code currently lives in our repo and fixed the issue.
> Ensure matched inserts sync to snowflake

- pyproject.toml
- src/koheesio/spark/transformations/debug.py
- tests/spark/transformations/test_debug.py
- tests/steps/test_http.py
This PR adds a Peek transformation that can be used during development and debugging of tasks.
It can be handy to inspect the schema / peek the content of the data during the development / debugging, more so if the data pipeline involves multiple transformation. The peek transformation can be inserted in the most critical sections to easily inspect the content or schema, and can be easily enabled / disabled using a flag so that it does not need to be removed from the pipeline when that is moved to a production environment.
Unit tests
> Peek transformation

- .github/workflows/test.yml
- pyproject.toml
- src/koheesio/spark/utils/common.py
- src/koheesio/spark/writers/buffer.py
- src/koheesio/steps/http.py
- tests/asyncio/test_asyncio_http.py
- tests/spark/readers/test_rest_api.py
- tests/spark/test_spark.py
- tests/steps/test_http.py
Improve spark logic for getActiveSession
> fix: ensure active Spark session retrieval only for supported versions
